### ISSUE TITLE
Bitcoin-ABC Release Tracking

### ISSUE THREAD

**Issue by bucko13** [bcoin-org/bcash#9]
[0.14.2](https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/doc/release-notes/release-notes-0.14.2.md)
- [x] DAA change that decreases difficulty if hashrate falls below 8%

[0.14.3](https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/doc/release-notes/release-notes-0.14.3.md)

- [ ] Update bitcoin-tx to produce replay protected signatures
- [ ] Update wallet to sign in replay protected manner once fork is active
- [ ] Command line help for 'uahfstarttime' option
- [ ] Fix a segmentation fault crash that could occur when peers disconnecting with high frequency (T64)

[0.14.4](https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/doc/release-notes/release-notes-0.14.4.md)

- [ ] Various code cleanups, refactorings, style and formatting changes
- [ ] Update block that's assumed to be valid
- [ ] Various test improvements
- [ ] Align ABC spec docs with UAHF specs of 2017-07-16
- [ ] Ensure that CDataStream never reads from empty buffers.

[0.14.5](https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/doc/release-notes/release-notes-0.14.5.md)

- [x] Enforce strong replay protection (require SIGHASH_FORKID and SCRIPT_VERIFY_STRICTENC compliance)
- [x] Change currency units in user interface from BTC -> BCC
- [x] Add NODE_BITCOIN_CASH service bit (0x20)
- [x] Update BU backed seeder to btccash-seeder.bitcoinunlimited.info
- [ ] Various refactoring and cleanups
- [ ] NOTE: Change in default value: 'forcednsseed' is enabled by default to increase chance of good connection to UAHF network (see D360)

[0.14.6](https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/doc/release-notes/release-notes-0.14.6.md)

- [x] Updated debian packaging
- [x] Updated FreeBSD build instructions
- [ ] Fix a bug where a node would erroneously increase the ban score of its peers when it hasn't caught up with the chain tip
- [ ] Added various detail about peer misbehaving
- [x] Added criptolayer.net DNS seeds

[0.15.0](https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/doc/release-notes/release-notes-0.15.0.md)

- [ ] Reserve block space for high priority transactions (D485)
- [x] Use "bitcoincash:" URI (D466)
- [x] Add and accept Bitcoin Cash networking magic (D400)
- [x] Peer preferentially with NODE_CASH nodes (D457) (see 0.16.2 for update)
- [x] Hardcoded seeds update (D403)
- [x] Remove UAHF RPC calls, and some of the UAHF activation logic (D407, D417)
- [x] Various test fixes and other cleanups now that UAHF activation is past
- [ ] Various changes now that we do replay protected txns only (D437, D440, D442, D444, D451, D455, D456)
- [x] Make SCRIPT_VERIFY_STRICTENC a mandatory flag (D421)
- [ ] Fix RPC signrawtransaction silently accepting missing amount field (D449)
- [ ] Fix a some small memory leaks, and an overflow (D372, D452, D472)
- [ ] Added sanitizer support (D474, D481)
- [ ] Cryptographic randomness improvements (backport from Core PR9821 and PR9792) (D488, D490)
- [x] Store the UTXO set on a per output basis rather than a per transaction basis (backport from Core)
- [ ] Various other backports and fixes from Core
- [ ] Various fixes and improvements to test suite
- [ ] Various code cleanups and style improvements
- [ ] Low level RPC error code changes (D500 / backport of PR9853)

[0.15.1](https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/doc/release-notes/release-notes-0.15.1.md)

- [ ] Cache script validation. Backport from Core 10192 (D527, D530, D531).
- [ ] Add Amount class for CENT and COIN (D529).
- [ ] Display if a node is using Cash magic in getpeerinfo (D546).
- [x] Use Cash magic by default when establishing connections (D547).
- [ ] Add seeder to Bitcoin ABC repository. From Bitcoin Seeder by Pieter Wiulle. (D559, D560, D561, D562, D564, D565, D566, D568, D579, D585)
- [ ] Ensure backupwallet fails if target is the same as source (D550).
- [x] Upgrade to LevelDB 1.20. Port of Core 10544 and 10958 (D580, D584).
- [ ] Various backports from Core.
- [ ] Various bug fixes.
- [ ] Various style fixes, code cleanups, and refactorings.

[0.16.0](https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/doc/release-notes/release-notes-0.16.0.md)

- [x] New difficulty adjustement algorithm due to activate on Nov, 13
- [ ] Start enforcing LOW_S and NULLFAIL after Nov, 13

[0.16.1](https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/doc/release-notes/release-notes-0.16.1.md)

- [x] Update seeds

[0.16.2](https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/doc/release-notes/release-notes-0.16.2.md)
- [ ] Remove the newdaaactivationtime configuration.
- [ ] Do not use the NODE_BITCOIN_CASH service bit for preferencial peering anymore.
- [ ] Only connect to node using the cash magic.
- [ ] Remove indicator mentionning if a node uses the cash magic getpeerinfo RPC.
- [x] Add support for the new cashaddr format. The -usecashaddr flag can be used to select which format is used when presenting addresses to users. By default, Bitcoin ABC will keep using the old format until Jan, 14 and then switch to the new format. Both format are now accepted as input.

[0.17.0](https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/doc/release-notes/release-notes-0.17.0.md)

- [x] Add monolithactivationtime configuration in order to chose when the May, 15 hard fork activates. This value should not be changed in production, but it allows user to test the fork activation ahead of time.
- [ ] dumpwallet no longer allows overwriting files. This is a security measure as well as prevents dangerous user mistakes.
- [ ] Node using the wrong magic are now getting banned.
- [ ] cmake builds are now possible for bitcoind and other utilities.
- [ ] Correct open source to open-source in README.md (Props to John Carvalho)
- [ ] Add SSE4 optimized SHA256 (Port from Bitcoin Core)
- [x] Multiwallet support (Port from Bitcoin Core)
- [ ] Lots of improvements to the RPC test suite (Ports from Bitcoin Core)
- [ ] Uptime rpc command (Port from Bitcoin Core)
- [x] At the MTP time of 1526400000 (Tue May 15 16:00:00 UTC, 2018) the following behaviors will change:
- [ ] Increase the default datacarriersize to 220 byte at the MTP time of 1526400000
- [x] Increase the maximum blocksize to 32,000,000 bytes at the MTP time of 1526400000
- [x] Re-activate the following opcodes: OP_CAT, OP_AND, OP_OR, OP_XOR, OP_DIV, OP_MOD
- [x] Add the following new opcodes: OP_SPLIT to replace OP_SUBSTR, OP_NUM2BIN, OP_BIN2NUM

**Comment by tuxcanfly** [comment]
OK, created issues for whatever we're missing. The remaining unchecked items are issues specific to bitcoin-abc.
